package otus.gpb.recyclerview.persistence

import otus.gpb.recyclerview.R
import otus.gpb.recyclerview.model.Chat

class Datasource {

    companion object {
        fun getMessages(pageSize: Int, pageNumber: Int): MutableList<Chat> {
            val data = getData()

            val startIndex = (pageNumber * pageSize).coerceAtMost(data.size)
            val endIndex = (startIndex + pageSize).coerceAtMost(data.size)

            return data.subList(startIndex, endIndex)
        }

        fun total() = getData().size

        private fun getData(): MutableList<Chat> {
            return mutableListOf(
                Chat(
                    avatar = R.drawable.jija_avatar,
                    chatName = R.string.pizza_chat_name,
                    messageAuthor = R.string.jija_message_author,
                    messageImage = R.drawable.mini_preview,
                    message = R.string.jija_message,
                    messageDate = R.string.jija_message_date,
                    verified = false,
                    mute = true,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 1,
                ),
                Chat(
                    avatar = R.drawable.elon_avatar,
                    chatName = R.string.elon_chat_name,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.elon_message,
                    messageDate = R.string.elon_message_date,
                    verified = false,
                    mute = true,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 0,
                ),
                Chat(
                    avatar = R.drawable.pasha,
                    chatName = R.string.pasha_chat_name,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.pasha_message,
                    messageDate = R.string.pasha_message_date,
                    verified = true,
                    mute = true,
                    deliveredStatus = null,
                    official = true,
                    newMessagesCount = 3,
                ),
                Chat(
                    avatar = R.drawable.telegram,
                    chatName = R.string.telegram_chat_name,
                    messageAuthor = R.string.telegram_message_author,
                    messageImage = null,
                    message = R.string.telegram_message,
                    messageDate = R.string.telegram_message_date,
                    verified = true,
                    mute = false,
                    deliveredStatus = null,
                    official = true,
                    newMessagesCount = 0,
                ),
                Chat(
                    avatar = R.drawable.karina,
                    chatName = R.string.karina_chat_name,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.karina_message,
                    messageDate = R.string.karina_message_date,
                    verified = false,
                    mute = false,
                    deliveredStatus = R.drawable.delivered,
                    official = false,
                    newMessagesCount = 5,
                ),
                Chat(
                    avatar = R.drawable.marilyn,
                    chatName = R.string.marilyn_chat_name,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.marilyn_message,
                    messageDate = R.string.marilyn_message_date,
                    verified = false,
                    mute = false,
                    deliveredStatus = R.drawable.read_icon,
                    official = false,
                    newMessagesCount = 20,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_1,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_2,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_3,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_4,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_5,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_6,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_7,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_8,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_9,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_10,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_11,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_12,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_13,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_14,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_15,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_16,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_17,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_18,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_19,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_20,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_21,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_22,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_23,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_24,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_25,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_26,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_27,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_28,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_29,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_30,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_31,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_32,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_33,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_34,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_35,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_36,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_37,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_38,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_39,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
                Chat(
                    avatar = R.drawable.comedy_mask_24px,
                    chatName = R.string.anonymous,
                    messageAuthor = null,
                    messageImage = null,
                    message = R.string.additional_message_40,
                    messageDate = R.string.unknown,
                    verified = false,
                    mute = false,
                    deliveredStatus = null,
                    official = false,
                    newMessagesCount = 100500,
                ),
            )
        }
    }
}
